[tool.poetry]
name = "pep8speaks"
version = "0.1.0"
description = ""
authors = ["Himanshu Mishra <himanshu@orkohunter.net>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
requests = "^2.28.2"
flask = "^2.2.2"
gunicorn = "^20.1.0"
pycodestyle = "^2.10.0"
flake8 = "^6.0.0"
pyyaml = "^6.0"
unidiff = "^0.7.4"
autopep8 = "^2.0.1"
markdown = "^3.4.1"
beautifulsoup4 = "^4.11.2"


[tool.poetry.group.dev.dependencies]
pytest = "^7.2.1"
pytest-flask = "^1.2.0"
pytest-mock = "^3.10.0"
mock = "^5.0.1"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
